# Generated by Django 3.1 on 2020-08-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200809_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='articles',
            field=models.ManyToManyField(to='blog.Article'),
        ),
    ]
